[build]
  # Build from repository root
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "trip-planner/build"
  
  # Custom build command
  command = "./build-netlify.sh"

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  CI = "false"
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"

# Production context
[context.production.environment]
  REACT_APP_ENV = "production"

# Deploy Preview context  
[context.deploy-preview.environment]
  REACT_APP_ENV = "preview"

# Branch deploy context
[context.branch-deploy.environment]
  REACT_APP_ENV = "branch"

# Redirect rules for single page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"